Feature/jacoco gh actions
AbsaOSS/spark-data-standardization pull request #48
Opened 2023-04-11 06:51 UTC by miroslavpojer

- Add new check gh action for jacoco measuring

2023-04-11 11:01 UTC, miroslavpojer commented
Milestone note:

- separated JaCoCo comments per Scala version
- added fake code (not used methods) to simulate changed files
- missing blocking results for PR

![image](https://user-images.githubusercontent.com/109138042/231140847-5329aef1-ebb4-442d-8687-bd562738609a.png)

2023-04-11 14:54 UTC, dk1844 reviewed
Outside of using snapshot version, ok.

2023-04-12 05:44 UTC, miroslavpojer commented on .github/workflows/jacoco_check.yml
> +            scalaShort: "2.12"
Yes, I was not able to find better/simple solution.

2023-04-12 05:47 UTC, miroslavpojer commented on project/plugins.sbt
> +lazy val jacocoVersion = "0.8.9-SNAPSHOT"
This is snapshot of Absa forked version. Jar libraries are manually added to Github "Release".

2023-04-12 05:49 UTC, miroslavpojer commented on project/plugins.sbt
> +addSbtPlugin("za.co.absa.sbt" % "sbt-jacoco" % "3.4.1-SNAPSHOT" from "https://github.com/AbsaOSS/sbt-jacoco/releases/download/3.4.1/sbt-jacoco.jar")
Same as comment above.

2023-04-12 05:50 UTC, miroslavpojer commented on .github/workflows/jacoco_check.yml
> +            core.setFailed('Overall coverage is less than 60%!')
Fixed in commit a457d4763d12b519467d15978f07e2066891127f.

2023-04-12 07:06 UTC, dk1844 commented on project/plugins.sbt
> +lazy val jacocoVersion = "0.8.9-SNAPSHOT"
Could such a vision materialize in an issue? (so that the _snapshot to be eventually replaced with a final version_ is not forever forgotten)

2023-04-12 08:00 UTC, dk1844 approved these changes
LGTM now (just read the code)

2023-04-12 08:19 UTC, dk1844 approved these changes
LGTM (just read the code)

2023-04-12 08:57 UTC, Zejnilovic approved these changes

2023-04-12 09:15 UTC, miroslavpojer commented on project/plugins.sbt
> +addSbtPlugin("za.co.absa.jacoco" % "report" % jacocoVersion from "https://github.com/AbsaOSS/jacoco/releases/download/0.8.9-absa.1/org.jacoco.report-0.8.9-absa.1.jar")
Fixed in commit 9cf49f0acd24e2d8073f21d54423f6972a7e7fc2.

2023-04-12 10:54 UTC, dk1844 commented on project/plugins.sbt
> +def ow2Url(keyword: String): String = s"https://repo1.maven.org/maven2/org/ow2/asm/$keyword/$ow2Version/$keyword-$ow2Version.jar"
```suggestion
def jacocoUrl(artifactName: String): String = s"https://github.com/AbsaOSS/jacoco/releases/download/$jacocoVersion/org.jacoco.$artifactName-$jacocoVersion.jar"
def ow2Url(artifactName: String): String = s"https://repo1.maven.org/maven2/org/ow2/asm/$keyword/$ow2Version/$artifactName-$ow2Version.jar"
```

2023-04-12 10:54 UTC, dk1844 commented on .github/workflows/jacoco_check.yml
> +        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
Do I assume the revert is intentional because the original value from `matrix.changed` could not be used?

2023-04-12 11:19 UTC, miroslavpojer commented on .github/workflows/jacoco_check.yml
> +        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
Yeah. I found it when copy-pasted to another project. Fixed in commit 1a5a89fa180b87e20ae6334e9118933d1a7c0cbe.

2023-04-13 07:57 UTC, dk1844 approved these changes
LGTM (just read the code)

2023-04-24 11:50 UTC, miroslavpojer commented on .github/workflows/jacoco_check.yml
> +# Copyright 2022 ABSA Group Limited
```suggestion
# Copyright 2023 ABSA Group Limited
```

2023-04-27 08:33 UTC, Zejnilovic approved these changes

2023-04-27 11:11 UTC, benedeki approved these changes

2023-04-28 11:10 UTC, benedeki requested changes

2023-04-28 11:10 UTC, benedeki commented on .github/workflows/jacoco_check.yml
> +            changed: 80.0
Would remove this. Spark 3 & Scala 2.12 are enough to check the coverage.

2023-04-28 11:10 UTC, benedeki commented on .github/workflows/jacoco_check.yml
> +            changed: 80.0
On second thought, this feels broken.
The overall being higher than partial will eventually lead to situation, that while the PR fulfills the partial coverage ratio, it brings the total bellow the boundary. So the PR is said to be good enough covered in its own, but in global context it is not....

2023-04-28 11:13 UTC, miroslavpojer commented on .github/workflows/jacoco_check.yml
> +            changed: 80.0
I will set overall to 0.0 as I did in another projects. Our main goal is to reach 80% coverage for changes.

2023-04-28 11:29 UTC, miroslavpojer commented on .github/workflows/jacoco_check.yml
> +            changed: 80.0
Combination removed in commit 02a59c6a792b73aea88f4a609f2957978f1c564c.

2023-04-28 11:30 UTC, miroslavpojer commented on .github/workflows/jacoco_check.yml
> +            changed: 80.0
Overall changed from 87 to 80 in commit 02a59c6a792b73aea88f4a609f2957978f1c564c.

2023-05-11 05:08 UTC, merged